module Arrays
	$monsters = [
		{'name'=>'Bulldrome', 'hp'=>500, 'icon'=>'bulldrome', 'trap'=>'both', 'color'=>'0x8b7657'},
		{'name'=>'Velocidrome', 'hp'=>500, 'icon'=>'velocidrome', 'trap'=>'both', 'color'=>'0x5193bd'},
		{'name'=>'Caeserber', 'hp'=>500, 'icon'=>'caeserber', 'trap'=>'both', 'color'=>'0xac8d45'},
		{'name'=>'Yian Kut-Ku', 'hp'=>500, 'icon'=>'yiankutku', 'trap'=>'both', 'color'=>'0xf57957'},
		{'name'=>'Gendrome', 'hp'=>500, 'icon'=>'gendrome', 'trap'=>'both', 'color'=>'0x588649'},
		{'name'=>'Baelidae', 'hp'=>500, 'icon'=>'baelidae', 'trap'=>'shock', 'color'=>'0x6a5577'},
		{'name'=>'Yellow Caeserber', 'hp'=>500, 'icon'=>'caeserber2', 'trap'=>'both', 'color'=>'0xc5cc6d'},
		{'name'=>'Gypceros', 'hp'=>500, 'icon'=>'gypceros', 'trap'=>'pitfall', 'color'=>'0x54657c'},
		{'name'=>'Congalala', 'hp'=>500, 'icon'=>'congalala', 'trap'=>'both', 'color'=>'0xc8979a'},
		{'name'=>'Chramine', 'hp'=>500, 'icon'=>'chramine', 'trap'=>'both', 'color'=>'0x664c2f'},
		{'name'=>'Cephadrome', 'hp'=>500, 'icon'=>'cephadrome', 'trap'=>'both', 'color'=>'0xb0985b'},
		{'name'=>'Daimyo Hermitaur', 'hp'=>500, 'icon'=>'daimyohermitaur', 'trap'=>'shock', 'color'=>'0xad4934'},
		{'name'=>'Blue Yian Kut-Ku', 'hp'=>700, 'icon'=>'yiankutku2', 'trap'=>'both', 'color'=>'0x569cc6'},
		{'name'=>'Khezu', 'hp'=>500, 'icon'=>'khezu', 'trap'=>'both', 'color'=>'0xc1bfc2'},
		{'name'=>'Basarios', 'hp'=>1000, 'icon'=>'basarios', 'trap'=>'both', 'color'=>'0x8699a0'},
		{'name'=>'Hypnocatrice', 'hp'=>1000, 'icon'=>'hypnocatrice', 'trap'=>'both', 'color'=>'0xde681f'},
		{'name'=>'Gold Congalala', 'hp'=>1000, 'icon'=>'congalala2', 'trap'=>'both', 'color'=>'0xf9c041'},
		{'name'=>'Dread Baelidae', 'hp'=>1000, 'icon'=>'baelidae2', 'trap'=>'shock', 'color'=>'0x91926a'},
		{'name'=>'Purple Gypceros', 'hp'=>1000, 'icon'=>'gypceros2', 'trap'=>'pitfall', 'color'=>'0x9f46d3'},
		{'name'=>'Shogun Ceanataur', 'hp'=>2000, 'icon'=>'shogunceanataur', 'trap'=>'shock', 'color'=>'0x365d84'},
		{'name'=>'Blangonga', 'hp'=>2000, 'icon'=>'blangonga', 'trap'=>'both', 'color'=>'0xefeed7'},
		{'name'=>'Estrellian', 'hp'=>2500, 'icon'=>'estrellian', 'trap'=>'no', 'color'=>'0x923023'},
		{'name'=>'Ice Chramine', 'hp'=>3000, 'icon'=>'chramine2', 'trap'=>'both', 'color'=>'0x5da8a3'},
		{'name'=>'Swordmaster Shogun Ceanataur', 'hp'=>3000, 'icon'=>'shogunceanataur', 'trap'=>'shock', 'color'=>'0x365d84'},
		{'name'=>'Akura Vashimu', 'hp'=>3000, 'icon'=>'akuravashimu', 'trap'=>'no', 'color'=>'0x99170e'},
		{'name'=>'Silver Hypnocatrice', 'hp'=>3000, 'icon'=>'hypnocatrice2', 'trap'=>'both', 'color'=>'0x7d8f95'},
		{'name'=>'Ghost Caeserber', 'hp'=>3000, 'icon'=>'caeserber', 'trap'=>'both', 'color'=>'0xac8d45'},
		{'name'=>'Crystal Basarios', 'hp'=>3000, 'icon'=>'basarios', 'trap'=>'both', 'color'=>'0x8699a0'},
		{'name'=>'Yian Garuga', 'hp'=>3000, 'icon'=>'yiangaruga', 'trap'=>'both', 'color'=>'76387e'},
		{'name'=>'Red Khezu', 'hp'=>3500, 'icon'=>'khezu2', 'trap'=>'both', 'color'=>'ac3141'},
		{'name'=>'One-Eared Yian Garuga', 'hp'=>3500, 'icon'=>'yiangaruga', 'trap'=>'both', 'color'=>'76387e'},
		{'name'=>'Doom Estrellian', 'hp'=>3500, 'icon'=>'estrellian2', 'trap'=>'no', 'color'=>'443193'},
		{'name'=>'Rathian', 'hp'=>3500, 'icon'=>'rathian', 'trap'=>'both', 'color'=>'12bf1d'},
		{'name'=>'Conflagration Rathian', 'hp'=>4000, 'icon'=>'rathian', 'trap'=>'both', 'color'=>'12bf1d'},
		{'name'=>'Tartaronis', 'hp'=>5000, 'icon'=>'tartaronis', 'trap'=>'no', 'color'=>'b69363'},
		{'name'=>'Rathalos', 'hp'=>4000, 'icon'=>'rathalos', 'trap'=>'both', 'color'=>'c2121e'},
		{'name'=>'Tigrex', 'hp'=>4000, 'icon'=>'tigrex', 'trap'=>'both', 'color'=>'eb7a06'},
		{'name'=>'Monoblos', 'hp'=>4000, 'icon'=>'monoblos', 'trap'=>'both', 'color'=>'e6af36'},
		{'name'=>'Shattered Monoblos', 'hp'=>4500, 'icon'=>'monoblos', 'trap'=>'both', 'color'=>'e6af36'},
		{'name'=>'Sandstone Basarios', 'hp'=>5000, 'icon'=>'basarios2', 'trap'=>'both', 'color'=>'988e84'},
		{'name'=>'Akura Jebia', 'hp'=>5000, 'icon'=>'akurajebia', 'trap'=>'no', 'color'=>'98adca'},
		{'name'=>'Azure Rathalos', 'hp'=>5000, 'icon'=>'rathalos2', 'trap'=>'both', 'color'=>'1186bc'},
		{'name'=>'Pink Rathian', 'hp'=>5000, 'icon'=>'rathian2', 'trap'=>'both', 'color'=>'e18793'},
		{'name'=>'Slicemargl', 'hp'=>5000, 'icon'=>'slicemargl', 'trap'=>'both', 'color'=>'1a4789'},
		{'name'=>'Diablos', 'hp'=>5000, 'icon'=>'diablos', 'trap'=>'both', 'color'=>'ac803c'},
		{'name'=>'Gold Hypnocatrice', 'hp'=>5000, 'icon'=>'hypnocatrice3', 'trap'=>'both', 'color'=>'d3a72a'},
		{'name'=>'Lightenna', 'hp'=>5000, 'icon'=>'lightenna', 'trap'=>'shock', 'color'=>'d3cb63'},
		{'name'=>'Kushala Daora', 'hp'=>5000, 'icon'=>'kushaladora', 'trap'=>'no', 'color'=>'3a3736'},
		{'name'=>'Merphistophelin', 'hp'=>5000, 'icon'=>'merphistophelin', 'trap'=>'no', 'color'=>'392c7c'},
		{'name'=>'White Monoblos', 'hp'=>5500, 'icon'=>'monoblos2', 'trap'=>'both', 'color'=>'dbd7cb'},
		{'name'=>'Flame Blangonga', 'hp'=>5500, 'icon'=>'blangonga2', 'trap'=>'both', 'color'=>'962a3f'},
		{'name'=>'Lavasioth', 'hp'=>5500, 'icon'=>'lavasioth', 'trap'=>'both', 'color'=>'537d9e'},
		{'name'=>'Purple Slicemargl', 'hp'=>5500, 'icon'=>'slicemargl2', 'trap'=>'both', 'color'=>'ee5697'},
		{'name'=>'Gravios', 'hp'=>5500, 'icon'=>'gravios', 'trap'=>'both', 'color'=>'867e6e'},
		{'name'=>'Chameleos', 'hp'=>5500, 'icon'=>'chameleos', 'trap'=>'no', 'color'=>'f575aa'},
		{'name'=>'Rajang', 'hp'=>6000, 'icon'=>'rajang', 'trap'=>'both', 'color'=>'968e66'},
		{'name'=>'GonnGenn Hermitaur', 'hp'=>6000, 'icon'=>'gonngennhermitaur', 'trap'=>'shock', 'color'=>'ffeb86'},
		{'name'=>'Elemental Merphistophelin', 'hp'=>6000, 'icon'=>'merphistophelin2', 'trap'=>'no', 'color'=>'cecece'},
		{'name'=>'Rusted Kushala Daora', 'hp'=>6000, 'icon'=>'kushaladora2', 'trap'=>'no', 'color'=>'79513b'},
		{'name'=>'Onimusha', 'hp'=>7000, 'icon'=>'onimusha', 'trap'=>'shock', 'color'=>'cfefea'},
		{'name'=>'Zinogre', 'hp'=>7000, 'icon'=>'zinogre', 'trap'=>'both', 'color'=>'bc9411'},
		{'name'=>'Berioros', 'hp'=>7500, 'icon'=>'', 'trap'=>'both', 'color'=>'910dc1'},
		{'name'=>'Arbiter Estrellian', 'hp'=>7500, 'icon'=>'estrellian3', 'trap'=>'no', 'color'=>'ae1c1c'},
		{'name'=>'Deviljho', 'hp'=>8000, 'icon'=>'deviljho', 'trap'=>'both', 'color'=>'586f65'},
		{'name'=>'Kirin', 'hp'=>8000, 'icon'=>'kirin', 'trap'=>'no', 'color'=>'a6e0f6'}
	]
	$items = [
		{'name'=>'Potion', 'image'=>'item_icon_01', 'throw'=>false, 'price'=>2000},
		{'name'=>'Antidote', 'image'=>'4', 'throw'=>false, 'price'=>2000},
		{'name'=>'Cool Drink', 'image'=>'item_icon_09', 'throw'=>false, 'price'=>2000},
		{'name'=>'Hot Drink', 'image'=>'item_icon_10', 'throw'=>false, 'price'=>2000},
		{'name'=>'Dash Juice', 'image'=>'item_icon_11', 'throw'=>false, 'price'=>2000},
		{'name'=>'Lifepowder', 'image'=>'item_icon_58', 'throw'=>true, 'price'=>2500},
		{'name'=>'Chilled Meat', 'image'=>'item_icon_17', 'throw'=>true, 'price'=>4000},
		{'name'=>'Hot Meat', 'image'=>'item_icon_18', 'throw'=>true, 'price'=>4000},
		{'name'=>'Poisoned Meat', 'image'=>'item_icon_22', 'throw'=>true, 'price'=>4000},
		{'name'=>'Drugged Meat', 'image'=>'item_icon_23', 'throw'=>true, 'price'=>4000},
		{'name'=>'Tinged Meat', 'image'=>'item_icon_24', 'throw'=>true, 'price'=>4000},
		{'name'=>'Vitality Agent', 'image'=>'item_icon_12', 'throw'=>false, 'price'=>3000},
		{'name'=>'Energy Drink', 'image'=>'item_icon_11', 'throw'=>false, 'price'=>2000},
		{'name'=>'Mega Nutrients', 'image'=>'item_icon_53', 'throw'=>false, 'price'=>4500},
		{'name'=>'Demondrug', 'image'=>'item_icon_10', 'throw'=>false, 'price'=>3000},
		{'name'=>'Armorskin', 'image'=>'item_icon_13', 'throw'=>false, 'price'=>3000},
		{'name'=>'Mega Potion', 'image'=>'item_icon_89', 'throw'=>false, 'price'=>5000},
		{'name'=>'Mega Demondrug', 'image'=>'item_icon_91', 'throw'=>false, 'price'=>5000},
		{'name'=>'Mega Nutrients', 'image'=>'item_icon_93', 'throw'=>false, 'price'=>5000},
		{'name'=>'Special Medicine', 'image'=>'item_icon_93', 'throw'=>false, 'price'=>3000},
		{'name'=>'Awakening', 'image'=>'item_icon_93', 'throw'=>false, 'price'=>2000},
		{'name'=>'Shock Trap', 'image'=>'item_icon_03', 'throw'=>false, 'price'=>10000},
		{'name'=>'Flash Bomb', 'image'=>'item_icon_06', 'throw'=>true, 'price'=>7500},
		{'name'=>'Sonic Bomb', 'image'=>'item_icon_07', 'throw'=>true, 'price'=>7500},
		{'name'=>'Paintball', 'image'=>'item_icon_25', 'throw'=>true, 'price'=>5000},
		{'name'=>'Smoke Bomb', 'image'=>'item_icon_81', 'throw'=>true, 'price'=>5000},
		{'name'=>'Deodorant', 'image'=>'item_icon_80', 'throw'=>true, 'price'=>7500},
		{'name'=>'Poison Smoke Bomb', 'image'=>'item_icon_82', 'throw'=>true, 'price'=>10000},
		{'name'=>'Farcaster', 'image'=>'item_icon_83', 'throw'=>true, 'price'=>10000},
		{'name'=>'Tranq Bomb', 'image'=>'item_icon_30', 'throw'=>true, 'price'=>7500},
		{'name'=>'Pitfall Trap', 'image'=>'item_icon_31', 'throw'=>false, 'price'=>10000},
		{'name'=>'Barrel Bomb S', 'image'=>'item_icon_37', 'throw'=>true, 'price'=>10000},
		{'name'=>'Barrel Bomb L', 'image'=>'item_icon_38', 'throw'=>true, 'price'=>15000},
		{'name'=>'Dung Bomb', 'image'=>'18', 'throw'=>true, 'price'=>7500},
		{'name'=>'Sonic Grenade', 'image'=>'item_icon_47', 'throw'=>true, 'price'=>5000},
		{'name'=>'Dynamite', 'image'=>'item_icon_38', 'throw'=>true, 'price'=>7500},
		{'name'=>'Pickaxe', 'image'=>'prop_tool_03', 'throw'=>true, 'price'=>3000},
		{'name'=>'Bug Net', 'image'=>'prop_tool_04', 'throw'=>false, 'price'=>3000},
		{'name'=>'Fishing Kit', 'image'=>'prop_tool_10', 'throw'=>false, 'price'=>3000}
	]
end
